[package]
name = "process_control"
version = "1.0.0"
authors = ["dylni"]
edition = "2018"
exclude = [".*", "/rustfmt.toml", "/tests"]
description = """
Methods for ergonomically running processes with timeouts
"""
repository = "https://github.com/dylni/process_control"
readme = "README.md"
keywords = ["process", "timeout", "time_out", "kill", "terminate"]
categories = ["concurrency", "os"]
license = "MIT OR Apache-2.0"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["handleapi", "processthreadsapi", "synchapi", "winbase", "winerror"] }

[build-dependencies]
cc = "1.0"
